### ISSUE TITLE
Current lesson body max length of 65,535 causes a lot of lag.

### ISSUE THREAD

**Issue by DamnTsun** [DamnTsun/EduWebPlatform_client#25]
The application become very slow and unresponsive when a lesson has a body that is over ~30,000 characters long.
This is noticeable both on the lesson creator/editor (if pasting in a tonne of characters), or when loading a lesson with such a high number of characters.
This is likely due to the Markdown rendering, as this is present on both pages.

Give how the system can support many lessons per topic, it may be a good idea to reduce lesson max length from 65,535 (2^16) to 16,384 (2^14).
This should mitigate the slowdown whilst still being long enough for lessons to contain a good amount of content. If this is insufficient, it is likely the creator should probably be putting the content over multiple lessons anyway...

**Comment by srichards96** [comment]
Now limited to 16000ish
